version: '3'
services:
    pdf-webservice:
        container_name: file.webservice
        hostname: file.webservice
        build:
          context: ./pdf-webservice
          dockerfile: ./src/main/docker/Dockerfile.jvm
        volumes:
          - /tmp/pdf-webservice:/pdf-webservice
        ports:
          - "8089:8089"
        restart: always
        depends_on:
          - file-middleware
          - file-storage-service
          - file-properties-service
          - keycloak
    file-middleware:
        container_name: file.middleware
        hostname: file.middleware
        build:
          context: ./file-middleware
          dockerfile: ./src/main/docker/Dockerfile.jvm
        volumes:
          - /tmp/file-middleware:/file-middleware
        ports:
          - "8080:8080"
        depends_on:
          - file-properties-service
          - file-storage-service
    file-properties-service:
        container_name: file.properties.service
        hostname: file.properties.service
        build:
          context: ./file-properties-service
          dockerfile: ./src/main/docker/Dockerfile.jvm
        volumes:
          - /tmp/file-properties-service:/file-properties-service
        ports:
          - "8082:8082"
    file-storage-service:
        hostname: file.storage.service
        container_name: file.storage.service
        build:
          context: ./file-storage-service
          dockerfile: ./src/main/docker/Dockerfile.jvm
        volumes:
          - /tmp/file-storage-service:/file-storage-service
        ports:
          - "8081:8081"
    postgres:
        image: postgres
        volumes:
          - postgres_data:/tmp/lib/postgresql/data
        environment:
          POSTGRES_DB: keycloak
          POSTGRES_USER: keycloak
          POSTGRES_PASSWORD: password
    keycloak:
        container_name: keycloak
        hostname: keycloak
        user: "1001"
        volumes:
          - ./realms:/opt/jboss/keycloak/imports
        image: quay.io/keycloak/keycloak:latest
        environment:
          DB_VENDOR: POSTGRES
          DB_ADDR: postgres
          DB_DATABASE: keycloak
          DB_USER: keycloak
          DB_SCHEMA: public
          DB_PASSWORD: password
          KEYCLOAK_USER: admin
          KEYCLOAK_PASSWORD: admin
        command:
          - "-Djboss.http.port=8180 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
        ports:
          - "8180:8180"
        depends_on:
          - postgres
volumes:
  postgres_data:
    driver: local  # is already local by default