openapi: 3.0.0
info:
  title: File Properties API
  description: File properties dto description
  version: 0.1.9
paths:
  /properties-service/get-file-properties:
    get:
      summary: placeholder.
      description: placeholder
      responses:
        '200':
          description: placeholder
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
components:
  schemas:
    FilePropertiesDTO:
      type: object
      properties:
        id:
          type: long
        fileName:
          type: string
        fileOwner:
          type: string
        dateUploaded:
          type: string
        fileIdentifier:
          type: string
